# Generated by Django 2.2 on 2023-02-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='code', max_length=100)),
                ('title', models.CharField(db_column='Title1', max_length=100)),
            ],
            options={
                'db_table': 'CourseData',
            },
        ),
    ]
